/* 國際設計比賽資料 — ported from competitionsData.ts. → window.COMPS
   "today" tracks the real current date so statuses & countdowns stay live. */
(function () {
  const TODAY = new Date();

  const competitions = [
    { id:"intl-poster-2026", name:"INTL 國際海報比賽 2026", nameEn:"INTL International Poster Competition 2026", organizer:"INTL International", country:"英國", website:"https://intl.international/posters/", description:"年度國際海報公開徵集，展示當代最佳海報設計作品。入選作品將於國際巡迴展覽展出，並收錄於年度專刊。", registrationOpen:"2026-01-12", deadline:"2026-06-01", entryFee:"£20／件", eligibility:"全球開放，不限資格", maxEntries:"每人最多 8 件", format:"靜態海報 JPG/PNG（寬≤2000px, ≤5MB）；動態海報 GIF/MP4（≤20MB, ≤15秒）", prizes:"第一名 £500、第二名 £300、第三名 £200", tags:["海報","年度","英國"] },
    { id:"graphis-poster-2027", name:"Graphis 海報獎 2027", nameEn:"Graphis Poster Awards 2027", organizer:"Graphis Inc.", country:"美國", website:"https://graphis.com/competition/poster-awards-2027/info", description:"Graphis 是全球最具聲望的設計獎項之一，海報類別涵蓋商業海報、文化海報、社會議題海報等。獲獎作品將刊載於 Graphis 年鑑。", deadline:"2026-03-10", entryFee:"單件 $140（會員 $70）；系列 $280（會員 $140）", eligibility:"全球開放，專業設計師與工作室", format:"高解析度 JPG/PDF", prizes:"金獎、銀獎、鉑金獎 — 刊載於 Graphis 年鑑與線上展覽", tags:["海報","年鑑","美國","高端"] },
    { id:"bicm-19", name:"第 19 屆墨西哥國際海報雙年展", nameEn:"19th BICM International Poster Biennial in Mexico", organizer:"Bienal Internacional del Cartel en México", country:"墨西哥", website:"https://bienalcartel.org/", description:"拉丁美洲最重要的海報設計雙年展，分為已出版海報、社會議題海報（地球修復／兒童權利／運動與和平文化）等類別。", theme:"A: 已出版海報 / B: 地球修復 / C: 兒童與青年權利 / D: 運動與和平文化", registrationOpen:"2026-01-31", deadline:"2026-03-31", entryFee:"報名免費；入選後 $20 USD／件", eligibility:"全球開放", prizes:"最高獎金 150,000 墨西哥披索（約 $8,500 USD）", tags:["海報","雙年展","墨西哥","社會議題"] },
    { id:"terras-gauda-2026", name:"Terras Gauda 國際海報設計雙年展 2026", nameEn:"International Biennial Poster Design Terras Gauda 2026", organizer:"Francisco Mantecón Foundation", country:"西班牙", website:"https://www.franciscomantecon.com/", description:"西班牙知名國際海報設計雙年展，面向全球開放，鼓勵創新的海報設計表達方式。", deadline:"2026-04-10", entryFee:"免費（現場列印服務 €15／張）", eligibility:"全球開放，年滿 18 歲", format:"數位檔案提交", tags:["海報","雙年展","西班牙","免費"] },
    { id:"golden-bee-17", name:"Golden Bee 17 全球平面設計雙年展", nameEn:"Golden Bee 17 Global Biennale of Graphic Design", organizer:"Golden Bee Foundation", country:"國際", website:"https://2026.goldenbee.org/en/", description:"全球最具影響力的平面設計雙年展之一，接受 2024-2026 年間創作的作品，涵蓋海報、書籍設計、品牌識別等類別。", deadline:"2026-04-17", entryFee:"免費", eligibility:"全球開放", maxEntries:"每人最多 3 件", tags:["平面設計","雙年展","免費","國際"] },
    { id:"a-design-award", name:"A' Design Award 海報類", nameEn:"A' Design Award — Poster, Flyer and Brochures", organizer:"A' Design Award & Competition", country:"義大利", website:"https://competition.adesignaward.com/posters.html", description:"全球最大的設計獎項之一，海報類別接受商業海報、文化海報、社會海報等。獲獎者將獲得獎盃、證書、媒體曝光及米蘭展覽機會。", deadline:"2026-02-28", resultsDate:"2026-04-15", entryFee:"依帳戶類型與截止日不同，約 €100–€580", eligibility:"全球開放，設計師、工作室、企業", prizes:"鉑金獎、金獎、銀獎、銅獎 — 獎盃 + 米蘭展覽 + 年鑑 + 媒體曝光", tags:["綜合設計","年度","義大利","高端"] },
    { id:"red-dot-bcd", name:"Red Dot Award: 品牌與傳達設計", nameEn:"Red Dot Award: Brands & Communication Design", organizer:"Red Dot GmbH & Co. KG", country:"德國", website:"https://www.red-dot.org/bcd/termine-kosten", description:"Red Dot 紅點獎是全球最知名的設計獎項之一。品牌與傳達設計類別涵蓋海報、品牌識別、包裝、數位媒體等。", registrationOpen:"2026-01-26", deadline:"2026-04-24", entryFee:"早鳥 €250；一般 €330（不含稅）", eligibility:"全球開放，專業設計師、工作室、企業", prizes:"Red Dot 標章、Best of the Best、Grand Prix — 全球展覽 + 年鑑", tags:["綜合設計","年度","德國","高端"] },
    { id:"if-design-2027", name:"iF Design Award 2027", nameEn:"iF Design Award 2027", organizer:"iF International Forum Design GmbH", country:"德國", website:"https://ifdesign.com/en/if-design-award-and-jury", description:"iF 設計獎是全球歷史最悠久的設計獎項之一（1954 年創立），涵蓋產品、傳達、包裝、室內、專業概念、服務設計及建築等類別。", deadline:"2026-11-05", entryFee:"早鳥 €350；一般 €400；末班車 €450", eligibility:"全球開放", resultsDate:"2027-04-01", prizes:"iF Gold Award — 獎盃 + 全球展覽 + 媒體曝光", tags:["綜合設計","年度","德國","高端"] },
    { id:"busan-design-2026", name:"2026 釜山國際設計獎", nameEn:"2026 International Busan Design Award", organizer:"Busan Design Center", country:"韓國", website:"https://adp.dcb.or.kr/en/ibda/hosting-guidelines", description:"韓國釜山主辦的國際設計獎，涵蓋視覺傳達、產品設計、空間設計等類別，鼓勵亞洲與全球設計交流。", deadline:"2026-04-22", entryFee:"依類別不同", eligibility:"全球開放", tags:["綜合設計","年度","韓國"] },
    { id:"artention-prague", name:"ARTtention 布拉格國際海報節", nameEn:"ARTtention Prague International Poster Festival", organizer:"ARTtention", country:"捷克", website:"https://www.arttention.eu/", description:"布拉格國際海報節，2026 年主題為「人類的孩子」，副標題「所有的孩子都是我們的孩子」，聚焦兒童權利與福祉議題。", theme:"The Children of People — All Children Are Our Children", deadline:"2026-04-10", entryFee:"依類別不同", eligibility:"全球開放", tags:["海報","藝術節","捷克","社會議題"] },
    { id:"plaster-17", name:"第 17 屆 PLASTER 國際平面設計節", nameEn:"17th International Graphic Design Festival PLASTER", organizer:"PLASTER Festival", country:"波蘭", website:"https://www.posterterritory.com/", description:"波蘭知名的國際平面設計節，每年吸引全球設計師參與，展示最新的平面設計趨勢與實驗性作品。", deadline:"2026-04-12", entryFee:"依類別不同", eligibility:"全球開放", tags:["平面設計","藝術節","波蘭"] },
    { id:"paste-up-warsaw", name:"PASTE UP WARSAW 2026 海報節", nameEn:"PASTE UP WARSAW 2026 Poster Festival", organizer:"PASTE UP", country:"波蘭", website:"https://pasteupwarsaw.com/", description:"華沙街頭海報藝術節，鼓勵設計師將海報帶入城市公共空間，探索海報與城市環境的互動關係。", deadline:"2026-04-30", entryFee:"免費", eligibility:"全球開放", tags:["海報","藝術節","波蘭","免費","街頭藝術"] },
    { id:"posterist-5", name:"第 5 屆 Posterist 展覽", nameEn:"The 5th Posterist Exhibition", organizer:"Posterist", country:"國際", website:"https://posterist.org/", description:"以社會議題為核心的國際海報展覽，2026 年主題為「社群媒體成癮」，探討數位時代對人類行為與心理健康的影響。", theme:"Social Media Addiction — 社群媒體成癮", deadline:"2026-05-03", entryFee:"依類別不同", eligibility:"全球開放", tags:["海報","展覽","社會議題"] },
    { id:"comm-arts-design", name:"Communication Arts 設計競賽", nameEn:"Communication Arts Design Competition", organizer:"Communication Arts Magazine", country:"美國", website:"https://www.commarts.com/", description:"美國最具影響力的設計雜誌 Communication Arts 主辦的年度設計競賽，獲獎作品將刊載於 CA 年鑑，是設計界的重要榮譽。", deadline:"2026-05-08", entryFee:"約 $50–$85／件", eligibility:"全球開放", prizes:"刊載於 Communication Arts 年鑑", tags:["綜合設計","年度","美國","年鑑"] },
    { id:"icons-freedom-2026", name:"Icons of Freedom: TRUTH — 國際海報比賽", nameEn:"2nd International Poster Competition Icons of Freedom: TRUTH — Iłża 2026", organizer:"Icons of Freedom", country:"波蘭", website:"https://www.posterterritory.com/the-2nd-international-poster-competition-icons-of-freedom-truth-ilza-2026/", description:"以「自由」為核心的國際海報比賽，2026 年主題為「真相」，探討後真相時代中真實與虛假的界線。", theme:"TRUTH — 真相", deadline:"2026-05-24", entryFee:"免費", eligibility:"全球開放", tags:["海報","社會議題","波蘭","免費"] },
    { id:"tpam-armenia-2026", name:"亞美尼亞國際戲劇海報雙年展 2026", nameEn:"Theatrical Posters Armenia International Biennale 2026 (TPAM)", organizer:"ACT Cultural NGO", country:"亞美尼亞", website:"https://actcultural.com/theatrical-posters/", description:"全球知名的戲劇海報設計雙年展，聚焦戲劇、歌劇、芭蕾、音樂、舞蹈及表演藝術海報。入選作品將於葉里溫展出，並收錄於官方圖錄。評審團由 AGI 國際成員組成。", theme:"舞台海報：戲劇、歌劇、芭蕾、音樂、舞蹈、表演藝術", deadline:"2026-05-30", entryFee:"免費", eligibility:"全球開放，設計師、藝術家、劇團及組織", maxEntries:"每人最多 3 件（2024-2026 年創作）", format:"JPEG, 1200px（長邊）, RGB, 300dpi, ≤3MB", prizes:"Grand Prix + 2 個最佳海報獎 + 特別獎 + 榮譽提名", tags:["海報","雙年展","戲劇","表演藝術","免費","亞美尼亞"] },
    { id:"poster-for-4", name:"Poster For___. 國際海報比賽第 4 屆", nameEn:"4th International Poster For___. Competition", organizer:"Poster For___. & Partners", country:"國際", website:"https://posterfor.com/", description:"以開放主題為特色的國際海報比賽，鼓勵設計師以海報形式探索任何社會議題或個人表達。", deadline:"2026-06-30", entryFee:"$40 USD／件", eligibility:"全球開放", tags:["海報","開放主題","國際"] },
    { id:"asia-design-prize", name:"Asia Design Prize 亞洲設計獎", nameEn:"Asia Design Prize", organizer:"Asia Design Prize Committee", country:"韓國", website:"https://asiadesignprize.com/", description:"亞洲地區最具代表性的設計獎項之一，涵蓋產品、視覺傳達、空間、數位設計等多個類別。", deadline:"2026-09-30", entryFee:"專業 $290；學生 $75；企業 $320", eligibility:"全球開放", prizes:"Grand Prize、Winner、Finalist — 展覽 + 媒體曝光", tags:["綜合設計","年度","韓國","亞洲"] },
    { id:"taiwan-postar", name:"台灣國際海報新星獎", nameEn:"Taiwan International Poster Rising Star Award", organizer:"台灣海報設計協會", country:"台灣", website:"https://postar.taiwanposter.com/", description:"台灣海報設計協會主辦的國際海報獎，旨在發掘新銳海報設計人才，促進台灣與國際海報設計交流。", deadline:"2026-08-18", entryFee:"依類別不同（約 NT$500–1,000）", eligibility:"全球開放", tags:["海報","年度","台灣","新銳"] },
    { id:"warsaw-biennale", name:"華沙國際海報雙年展", nameEn:"International Poster Biennale in Warsaw", organizer:"Academy of Fine Arts in Warsaw", country:"波蘭", website:"https://warsawposterbiennale.com/", description:"全球歷史最悠久、最具聲望的海報雙年展（1966 年創立），被譽為海報設計界的「奧斯卡」。每兩年舉辦一次，下屆預計 2027 年。", deadline:"2027-01-31", entryFee:"依屆次公告", eligibility:"全球開放", prizes:"金獎、銀獎、銅獎 — 永久典藏於華沙海報博物館", tags:["海報","雙年展","波蘭","頂級","歷史悠久"] },
    { id:"toyama-triennial", name:"富山國際海報三年展", nameEn:"International Poster Triennial in Toyama", organizer:"Toyama Prefectural Museum of Art and Design", country:"日本", website:"https://www.pref.toyama.jp/", description:"日本最重要的國際海報展覽，每三年舉辦一次，與華沙雙年展並列為全球最具影響力的海報展覽之一。入選作品永久典藏於富山縣立美術館。", deadline:"2027-06-30", entryFee:"日本以外參賽者免費", eligibility:"全球開放", prizes:"大獎 100 萬日圓、銀獎 50 萬日圓", tags:["海報","三年展","日本","頂級","免費"] },
    { id:"golden-pin-2026", name:"金點設計獎 2026", nameEn:"Golden Pin Design Award 2026", organizer:"台灣設計研究院（TDRI）", country:"台灣", website:"https://goldenpin.org.tw/", description:"1981 年創立於台灣，現為全球華人市場最頂尖設計獎項之一。涵蓋產品設計、視覺傳達設計、包裝設計、空間設計等類別，致力於表彰具有文化底蘊與創新精神的優秀設計。", registrationOpen:"2026-03-11", deadline:"2026-07-15", resultsDate:"2026-12-01", entryFee:"早鳥 NT$4,500／件（5/13 前）；一般 NT$6,000／件", eligibility:"全球開放，作品須已量產或上市", maxEntries:"不限", format:"線上報名，上傳作品照片與設計說明", prizes:"金點設計獎標章、年度最佳設計獎", tags:["綜合設計","年度","台灣","華人","頂級"] },
    { id:"tigda-2026", name:"臺灣國際平面設計獎 2026", nameEn:"Taiwan International Graphic Design Award 2026", organizer:"經濟部 / 財團法人中國生產力中心", country:"台灣", website:"https://www.tigda.org.tw/", description:"全球五大海報設計獎項之一，分為『臺灣國際海報設計獎』與『臺灣國際企業識別設計獎』兩大獎項，設有特定主題、一般主題、企業識別系統、企業識別應用四個類別。", registrationOpen:"2026-02-15", deadline:"2026-07-15", resultsDate:"2026-11-29", entryFee:"免費", eligibility:"全球開放，不限資格", maxEntries:"每人每類別最多 5 件", format:"線上上傳 JPG（寬 1190×高 840px, ≤3MB）", prizes:"金獎 US$5,000、銀獎 US$3,000、銅獎 US$1,000", tags:["海報","平面設計","年度","台灣","頂級","免費"] },
    { id:"taiwan-topstar-2026", name:"台灣金星設計獎 2026", nameEn:"Taiwan Top Star Design Award 2026", organizer:"台灣金星設計獎執行委員會", country:"台灣", website:"https://www.taiwantopstar.com/", description:"以鼓勵臺灣設計能量為精神、拓展臺灣設計視野為基石的視覺設計獎項，涵蓋平面設計、包裝設計、海報設計、識別設計及插畫設計等類別。", registrationOpen:"2026-04-01", deadline:"2026-06-20", resultsDate:"2026-09-15", entryFee:"早鳥 NT$800／件；一般 NT$1,200／件", eligibility:"全球開放", maxEntries:"不限", format:"線上上傳作品圖檔與設計說明", prizes:"金星獎、銀星獎、銅星獎、評審特別獎", tags:["視覺設計","海報","年度","台灣"] },
    { id:"kw-design-26", name:"瓩設計獎 第 26 屆", nameEn:"kW Design Award 26th", organizer:"台灣電力公司", country:"台灣", website:"https://kwd.tw/", description:"以能源議題為核心的創意設計競賽，鼓勵透過平面海報、多媒體等形式傳達節能減碳與永續能源理念，適合學生與社會人士參加。", registrationOpen:"2025-10-02", deadline:"2026-03-11", entryFee:"免費", eligibility:"台灣在學學生及社會人士", format:"線上提交作品與報名資料", prizes:"金獎 NT$50,000、銀獎 NT$30,000、銅獎 NT$10,000", tags:["海報","能源","台灣","免費","學生"] },
    { id:"tisdc-2026", name:"臺灣國際學生設計競賽 2026", nameEn:"Taiwan International Student Design Competition 2026", organizer:"教育部", country:"台灣", website:"https://www.tisdc.org/", description:"教育部主辦的國際學生設計競賽，設有產品設計、視覺設計、數位動畫、建築與景觀設計四大類別，為全球規模最大的學生設計競賽之一。", registrationOpen:"2026-03-01", deadline:"2026-06-30", resultsDate:"2026-12-01", entryFee:"免費", eligibility:"全球在學學生（含應屆畢業生）", maxEntries:"每人每類別最多 3 件", format:"線上上傳作品圖檔與設計說明影片", prizes:"大獎 NT$400,000、金獎 NT$150,000、銀獎 NT$80,000", tags:["綜合設計","學生","年度","台灣","免費","頂級"] },
    { id:"taipei-design-2026", name:"臺北設計獎 2026", nameEn:"Taipei Design Award 2026", organizer:"臺北市政府產業發展局", country:"台灣", website:"https://taipeidaward.taipei/", description:"以『設計為改善城市生活的驅動力』為核心理念，設有工業設計、視覺傳達設計、公共空間設計三大類別，鼓勵以設計解決城市問題。", registrationOpen:"2026-05-01", deadline:"2026-07-31", resultsDate:"2026-11-15", entryFee:"免費", eligibility:"全球開放，不限資格", format:"線上報名，上傳作品圖檔與說明", prizes:"臺北設計金獎 NT$600,000、各類金獎 NT$150,000", tags:["綜合設計","城市設計","年度","台灣","免費"] },
    { id:"c-idea-2026", name:"C-IDEA 設計獎 2026", nameEn:"C-IDEA Design Award 2026", organizer:"C-IDEA 國際設計獎委員會", country:"台灣", website:"https://cidea-union.com/", description:"面向全球的綜合性設計獎項，涵蓋平面設計、產品設計、空間設計、時尚設計等多個類別，致力於發掘與推廣華人設計力量。", registrationOpen:"2025-09-25", deadline:"2026-03-31", entryFee:"報名費 US$80／件；入選後評審費另計", eligibility:"全球開放", format:"線上提交作品資料", prizes:"金獎、銀獎、銅獎、評審團特別獎", tags:["綜合設計","年度","台灣","華人"] },
  ];

  const statusLabels = { open:"徵件中", upcoming:"即將開放", closed:"已截止", ongoing:"常年開放" };
  const statusColors = {
    open:     { bg:"#e2f7ee", text:"#1fa877", dot:"#34d399" },
    upcoming: { bg:"#fdf2dc", text:"#b9831a", dot:"#fbbf24" },
    closed:   { bg:"#ececed", text:"#9a9aa0", dot:"#bdbdc4" },
    ongoing:  { bg:"#e6f0fe", text:"#3d82e6", dot:"#60a5fa" },
  };

  function status(c) {
    if (c.deadline === "ongoing") return "ongoing";
    const dl = new Date(c.deadline);
    if (c.registrationOpen && TODAY < new Date(c.registrationOpen)) return "upcoming";
    if (TODAY > dl) return "closed";
    return "open";
  }
  function daysLeft(deadline) {
    if (deadline === "ongoing") return null;
    return Math.ceil((new Date(deadline).getTime() - TODAY.getTime()) / 86400000);
  }
  function fmtDate(d) {
    if (d === "ongoing") return "常年開放";
    const dt = new Date(d);
    return `${dt.getFullYear()} 年 ${dt.getMonth() + 1} 月 ${dt.getDate()} 日`;
  }
  function feeValue(f) {
    if (f.includes("免費") || f.toLowerCase().includes("free")) return 0;
    const m = f.match(/[\d,]+/);
    return m ? parseInt(m[0].replace(/,/g, ""), 10) : 999;
  }

  window.COMPS = { competitions, statusLabels, statusColors, status, daysLeft, fmtDate, feeValue, TODAY };
})();
